#!/usr/bin/env python3

import json
import shutil
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "pypkg"))

from hermes_agent_state import AGENTS_DIR, container_name, list_known_agent_ids, remove_agent_state, service_unit


def run(command, check=True):
    subprocess.run(command, check=check)



json.load(sys.stdin)

for agent_id in list_known_agent_ids():
    run(["systemctl", "--user", "disable", "--now", service_unit(agent_id)], check=False)
    run(["podman", "rm", "--force", container_name(agent_id)], check=False)
    remove_agent_state(agent_id)

if AGENTS_DIR.exists():
    shutil.rmtree(AGENTS_DIR, ignore_errors=True)
